<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a4b92e4a-a868-4d2f-9889-3d2ebd91428f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobPortal.Persistence.Postgres\JobPortal.Persistence.Postgres.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobPortal.Application\JobPortal.Application.csproj" />
    <ProjectReference Include="..\JobPortal.Infrastructure\JobPortal.Infrastructure.csproj" />
    <ProjectReference Include="..\JobPortal.Persistence\JobPortal.Persistence.csproj" />
    <ProjectReference Include="..\JobPortal.Shared\JobPortal.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\migrate.yml" />
  </ItemGroup>

</Project>
