name: Run EF Migrations on Azure

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore solution
        run: dotnet restore

      - name: Install EF Tool
        run: dotnet tool install --global dotnet-ef

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Debug connection type
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION }}
        run: |
          echo "$ConnectionStrings__DefaultConnection" | grep -o "Server=[^;]*"

      - name: Run Migration
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION }}
          Jwt__Key: ${{ secrets.JWT_KEY }}
          Jwt__Issuer: "github-actions"
          Jwt__Audience: "github-actions"
          ASPNETCORE_ENVIRONMENT: Development
        run: |
          dotnet ef database update \
            --project JobPortal.Persistence \
            --startup-project JobPortal.API
